PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZQMALVCUST CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZQMALVCUST-ALV_TYPE .
    FIELD ZQMALVCUST-TCODE .
    FIELD ZQMALVCUST-FIELDNAME .
    FIELD ZQMALVCUST-EDITABLE .
    FIELD ZQMALVCUST-DROPDOWN_ENABLED .
    FIELD ZQMALVCUST-CUSTOM_COLUMN_HEADER .
    FIELD ZQMALVCUST-OUTPUTLEN .
    FIELD ZQMALVCUST-GROUP_VALUES .
    FIELD ZQMALVCUST-REF_FIELD .
    FIELD ZQMALVCUST-REF_TABLE .
    FIELD ZQMALVCUST-FIELD_POSITION .
    FIELD ZQMALVCUST-ACTIVE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   CHAIN.
    FIELD ZQMALVCUSTT-TEXT30 .
    MODULE SET_TXT_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZQMALVCUST-ALV_TYPE .
    FIELD ZQMALVCUST-TCODE .
    FIELD ZQMALVCUST-FIELDNAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
