FUNCTION Z_QM_NOTIF_LAB_CREATE.
*"----------------------------------------------------------------------
*"*"Lokale Schnittstelle:
*"  IMPORTING
*"     VALUE(I_VIQMEL) LIKE  VIQMEL STRUCTURE  VIQMEL
*"     VALUE(I_CUSTOMIZING) LIKE  V_TQ85 STRUCTURE  V_TQ85
*"  EXPORTING
*"     VALUE(E_QNQMAMA0) LIKE  QNQMAMA0 STRUCTURE  QNQMAMA0
*"  TABLES
*"      TI_IVIQMFE STRUCTURE  WQMFE
*"      TI_IVIQMUR STRUCTURE  WQMUR
*"      TI_IVIQMSM STRUCTURE  WQMSM
*"      TI_IVIQMMA STRUCTURE  WQMMA
*"      TI_IHPA STRUCTURE  IHPA
*"      TE_LINES STRUCTURE  TLINE OPTIONAL
*"  EXCEPTIONS
*"      ACTION_STOPPED
*"----------------------------------------------------------------------

  CONSTANTS: LC_NOTIF_TYPE TYPE BAPI2078-NOTIF_TYPE VALUE 'ZM'.
  DATA: LS_QMEL TYPE BAPI2078.
  DATA: LV_QMNUM_NEW TYPE BAPI2078-NOTIFICAT.
  DATA: LS_RETURN TYPE BAPIRETURN.
  DATA: ROLE_A TYPE BORIDENT,
        ROLE_B TYPE BORIDENT.
*
  LS_QMEL-NOTIF_TYPE = LC_NOTIF_TYPE.
  CALL FUNCTION 'BAPI_QNOTIFICAT_CREATE'
    EXPORTING
      NOTIF_HEADER = LS_QMEL
    IMPORTING
      NUMBER       = LV_QMNUM_NEW
      RETURN       = LS_RETURN.

  IF LS_RETURN-TYPE = 'E'.
    MESSAGE LS_RETURN-MESSAGE TYPE LS_RETURN-TYPE.
  ENDIF.

  CALL FUNCTION 'BAPI_TRANSACTION_COMMIT'
    EXPORTING
      WAIT = 'X'.


  IF LV_QMNUM_NEW IS NOT INITIAL.

    ROLE_A-OBJKEY = I_VIQMEL-QMNUM.
    ROLE_A-OBJTYPE = 'BUS2078'.

    ROLE_B-OBJKEY = LV_QMNUM_NEW.
    ROLE_B-OBJTYPE = 'BUS2078'.
    " --------------------
    " Belegverweis anlegen
    " --------------------
    CALL FUNCTION 'QMLR_CREATE_DOCUMENT_FLOW'
      EXPORTING
        ROLE_A  = ROLE_A
        ROLE_B  = ROLE_B
        RELTYPE = 'LINK'
      EXCEPTIONS
        OTHERS  = 1.
    IF SY-SUBRC IS NOT INITIAL.
      MESSAGE E103(ZQM).
    ENDIF.

    UPDATE QMEL SET ZZPSPEL = I_VIQMEL-ZZPSPEL
    WHERE QMNUM = LV_QMNUM_NEW.

  ENDIF.
  E_QNQMAMA0-MATXT = LV_QMNUM_NEW.
  SET PARAMETER ID 'IQM' FIELD LV_QMNUM_NEW.
  CALL TRANSACTION 'QM02' AND SKIP FIRST SCREEN.
ENDFUNCTION.
