FUNCTION Z_QM_BMS_ANALYSIS_REP.
*"--------------------------------------------------------------------
*"*"Lokale Schnittstelle:
*"  IMPORTING
*"     VALUE(I_VIQMEL) LIKE  VIQMEL STRUCTURE  VIQMEL
*"     VALUE(I_CUSTOMIZING) LIKE  V_TQ85 STRUCTURE  V_TQ85
*"  EXPORTING
*"     VALUE(E_QNQMAMA0) LIKE  QNQMAMA0 STRUCTURE  QNQMAMA0
*"  TABLES
*"      TI_IVIQMFE STRUCTURE  WQMFE
*"      TI_IVIQMUR STRUCTURE  WQMUR
*"      TI_IVIQMSM STRUCTURE  WQMSM
*"      TI_IVIQMMA STRUCTURE  WQMMA
*"      TI_IHPA STRUCTURE  IHPA
*"      TE_LINES STRUCTURE  TLINE OPTIONAL
*"  EXCEPTIONS
*"      ACTION_STOPPED
*"--------------------------------------------------------------------
  CONSTANTS: LC_MEM_ID_0505 TYPE CHAR40 VALUE 'GT_PROBES_0505',
             LC_DOC_TYPE TYPE AUART VALUE 'ZFRE'.


  DATA: LT_QMCRM      TYPE TABLE OF ZZQMCRM,
        LS_QMCRM      TYPE ZZQMCRM.
  DATA: LV_VBELN      TYPE VBELN,
        LV_MATNR      TYPE MATNR,
        LV_VKORG      TYPE VKORG,
        LV_VTWEG      TYPE VTWEG,
        LV_SPART      TYPE SPART,
        LV_VKBUR      TYPE VKBUR,
        LV_KUNAG      TYPE KUNAG.
  DATA: LS_VBAK       TYPE BAPISDHD1,
        LT_RETURN     TYPE TABLE OF BAPIRET2,
        LS_RETURN     TYPE BAPIRET2,
        LT_VBAP       TYPE TABLE OF BAPISDITM,
        LS_VBAP       TYPE BAPISDITM,
        LT_VBAPX      TYPE TABLE OF BAPISDITMX,
        LT_VBPA       TYPE TABLE OF BAPIPARNR,
        LS_VBPA       TYPE BAPIPARNR,
        LT_VBEP       TYPE TABLE OF BAPISCHDL,
        LS_VBEP       TYPE BAPISCHDL,
        lv_itm_numb   type vbap-posnr.
  DATA: ROLE_A TYPE BORIDENT,
        ROLE_B TYPE BORIDENT.

*  "get probes table from include ZXQQMI05
  IMPORT GT_QMCRM_0505 TO LT_QMCRM FROM MEMORY ID LC_MEM_ID_0505.
  FREE MEMORY ID LC_MEM_ID_0505.
* Read parameter
  READ TABLE LT_QMCRM WITH KEY MARK = 'X' TRANSPORTING NO FIELDS.
  IF SY-SUBRC IS NOT INITIAL.
    MESSAGE E100(ZQM).

* Read parameter
  ELSE.
    LOOP AT LT_QMCRM INTO LS_QMCRM WHERE MARK IS NOT INITIAL.
      lv_itm_numb = lv_itm_numb + 10.
      SELECT SINGLE VKORG VTWEG SPART FROM VBRK INTO (LV_VKORG, LV_VTWEG, LV_SPART)
        WHERE  VBELN = LS_QMCRM-FAKNR.
      IF SY-SUBRC IS INITIAL.
        IF LS_VBAK-SALES_ORG IS INITIAL.
          LS_VBAK-SALES_ORG = LV_VKORG.
          LS_VBAK-DISTR_CHAN = LV_VTWEG.
          LS_VBAK-DIVISION = LV_SPART.
          LS_VBAK-DOC_TYPE = LC_DOC_TYPE.
        ELSEIF LS_VBAK-SALES_ORG NE LV_VKORG OR LS_VBAK-DISTR_CHAN NE LV_VTWEG.
          MESSAGE E101(ZQM).
        ENDIF.
        LS_VBAP-MATERIAL = LS_QMCRM-MATNR.
        LS_VBAP-BATCH = LS_QMCRM-BALLEN_ID.
        LS_VBAP-TARGET_QTY = LS_QMCRM-WEIGHT.
        LS_VBAP-TARGET_QU = 'K13'.
        LS_VBAP-PLANT = LS_QMCRM-WERKS.
        ls_vbap-itm_number = lv_itm_numb.
        APPEND LS_VBAP TO LT_VBAP.
        LS_VBEP-ITM_NUMBER = LS_VBAP-ITM_NUMBER.
        LS_VBEP-REQ_QTY = LS_VBAP-TARGET_QTY.
        APPEND LS_VBEP TO LT_VBEP.
      ELSE.
        MESSAGE E102(ZQM).
      ENDIF.
    ENDLOOP.

    IF LS_VBAK IS NOT INITIAL AND LT_VBAP[] IS NOT INITIAL.
      SELECT PARVW KUNNR FROM VBPA
        INTO (LS_VBPA-PARTN_ROLE, LS_VBPA-PARTN_NUMB)
        WHERE VBELN = LS_QMCRM-VBELN
        AND ( PARVW = 'WE' OR PARVW = 'AG' )
        .
        APPEND LS_VBPA TO LT_VBPA.
      ENDSELECT.

      CALL FUNCTION 'BAPI_CUSTOMERRETURN_CREATE'
        EXPORTING
          RETURN_HEADER_IN    = LS_VBAK
        IMPORTING
          SALESDOCUMENT       = LV_VBELN
        TABLES
          RETURN              = LT_RETURN
          RETURN_ITEMS_IN     = LT_VBAP
          RETURN_ITEMS_INX    = LT_VBAPX
          RETURN_PARTNERS     = LT_VBPA
          RETURN_SCHEDULES_IN = LT_VBEP.
    ENDIF.
    LOOP AT LT_RETURN INTO LS_RETURN WHERE TYPE = 'E'.
      MESSAGE LS_RETURN-MESSAGE TYPE LS_RETURN-TYPE.
    ENDLOOP.

    CALL FUNCTION 'BAPI_TRANSACTION_COMMIT'
      EXPORTING
        WAIT = 'X'.
    IF SY-SUBRC = 0.
      ROLE_A-OBJKEY = I_VIQMEL-QMNUM.
      ROLE_A-OBJTYPE = 'BUS2078'.

      ROLE_B-OBJKEY = LV_VBELN.
      ROLE_B-OBJTYPE = 'BUS2102'.
      " --------------------
      " Belegverweis anlegen
      " --------------------
      CALL FUNCTION 'QMLR_CREATE_DOCUMENT_FLOW'
        EXPORTING
          ROLE_A  = ROLE_A
          ROLE_B  = ROLE_B
          RELTYPE = 'REFZ'
        EXCEPTIONS
          OTHERS  = 1.
      IF SY-SUBRC IS NOT INITIAL.
        MESSAGE E103(ZQM).
      ENDIF.
    ELSE.
      MESSAGE E104(ZQM).
    ENDIF.

    IF LV_VBELN IS NOT INITIAL.
      E_QNQMAMA0-MATXT = LV_VBELN.
      LOOP AT LT_QMCRM INTO LS_QMCRM WHERE MARK = 'X'.
        UPDATE ZZQMCRM SET RETOURENAUFTRAG = LV_VBELN
        WHERE BALLEN_ID = LS_QMCRM-BALLEN_ID
        AND WERKS = LS_QMCRM-WERKS.
      ENDLOOP.
      SET PARAMETER ID 'AUN' FIELD LV_VBELN.
      CALL TRANSACTION 'VA02' AND SKIP FIRST SCREEN.
    ENDIF.
  ENDIF.
ENDFUNCTION.
